import type {
  GeoEvent,
  AIAgent,
  IntelligenceReport,
  StreamEvent,
  NetworkNode,
  ThreatZone,
  TimelineEntry,
  SystemMetric,
  Mission,
} from "./types";

export const MOCK_GEO_EVENTS: GeoEvent[] = [
  {
    id: "evt-001",
    title: "Electronic Warfare Activity — Eastern Front",
    summary:
      "Elevated signals intelligence detected along disputed corridor. GPS spoofing operations confirmed in three sectors.",
    category: "MILITARY",
    threat: "HIGH",
    lat: 49.8,
    lng: 36.2,
    country: "Ukraine",
    region: "Eastern Europe",
    timestamp: new Date(Date.now() - 1000 * 60 * 4),
    confidence: 87,
    sources: ["SIGINT", "OSINT", "Sentinel-2 SAR"],
    tags: ["EW", "GPS spoofing", "front line"],
    affectedPopulation: 2100000,
  },
  {
    id: "evt-002",
    title: "Cyber Intrusion — Critical Infrastructure",
    summary:
      "APT-41 fingerprint detected in power grid SCADA systems. Multi-vector attack targeting supervisory control networks.",
    category: "CYBER",
    threat: "CRITICAL",
    lat: 40.7,
    lng: -74.0,
    country: "United States",
    region: "North America",
    timestamp: new Date(Date.now() - 1000 * 60 * 11),
    confidence: 94,
    sources: ["CISA Alert", "Darknet Monitoring", "Honeypot Network"],
    tags: ["APT-41", "SCADA", "power grid", "infrastructure"],
    affectedPopulation: 8400000,
  },
  {
    id: "evt-003",
    title: "Strait of Hormuz Naval Incident",
    summary:
      "Three commercial vessels shadowed by patrol boats in international waters. AIS spoofing detected on two IRGCN assets.",
    category: "MILITARY",
    threat: "HIGH",
    lat: 26.5,
    lng: 56.3,
    country: "Iran",
    region: "Middle East",
    timestamp: new Date(Date.now() - 1000 * 60 * 23),
    confidence: 79,
    sources: ["MarineTraffic", "IMINT", "HUMINT"],
    tags: ["naval", "shipping lanes", "IRGCN", "AIS spoofing"],
    affectedPopulation: 0,
  },
  {
    id: "evt-004",
    title: "Disinformation Campaign Escalation",
    summary:
      "Coordinated narrative injection detected across 47 state media outlets. AI-generated content flooding social platforms.",
    category: "INTELLIGENCE",
    threat: "MEDIUM",
    lat: 55.7,
    lng: 37.6,
    country: "Russia",
    region: "Eastern Europe",
    timestamp: new Date(Date.now() - 1000 * 60 * 38),
    confidence: 91,
    sources: ["Open Source", "Social Media Analytics", "NLP Pipeline"],
    tags: ["disinformation", "IO", "synthetic media", "influence ops"],
    affectedPopulation: 145000000,
  },
  {
    id: "evt-005",
    title: "North Korea ICBM Engine Test",
    summary:
      "Infrared signature consistent with Paektusan-class engine detected at Sohae launch facility. Pre-launch indicators elevated.",
    category: "MILITARY",
    threat: "CRITICAL",
    lat: 40.0,
    lng: 124.7,
    country: "North Korea",
    region: "East Asia",
    timestamp: new Date(Date.now() - 1000 * 60 * 58),
    confidence: 83,
    sources: ["NRO IMINT", "Seismic Network", "OSINT"],
    tags: ["ICBM", "nuclear", "Sohae", "test"],
    affectedPopulation: 0,
  },
  {
    id: "evt-006",
    title: "South China Sea Reef Construction",
    summary:
      "New concrete structures identified on disputed atoll. Helicopter landing pad and radar installations under construction.",
    category: "GEOPOLITICAL",
    threat: "MEDIUM",
    lat: 11.9,
    lng: 114.3,
    country: "China",
    region: "Southeast Asia",
    timestamp: new Date(Date.now() - 1000 * 60 * 75),
    confidence: 96,
    sources: ["Planet Labs", "Sentinel-1", "OSINT"],
    tags: ["SCS", "artificial island", "militarization"],
    affectedPopulation: 0,
  },
  {
    id: "evt-007",
    title: "Ransomware — Hospital Network",
    summary:
      "LockBit 4.0 variant encrypting EHR systems across 12 hospitals. 340,000 patient records at risk. Ransom demand: $28M.",
    category: "CYBER",
    threat: "HIGH",
    lat: 51.5,
    lng: -0.12,
    country: "United Kingdom",
    region: "Western Europe",
    timestamp: new Date(Date.now() - 1000 * 60 * 95),
    confidence: 99,
    sources: ["NCSC Alert", "Dark Web Monitor", "IR Team"],
    tags: ["ransomware", "LockBit", "healthcare", "critical"],
    affectedPopulation: 340000,
  },
  {
    id: "evt-008",
    title: "Sahel Humanitarian Crisis",
    summary:
      "Food insecurity reaching catastrophic levels in three provinces. Armed group activity blocking aid convoys on primary routes.",
    category: "HUMANITARIAN",
    threat: "HIGH",
    lat: 15.5,
    lng: 2.1,
    country: "Mali",
    region: "West Africa",
    timestamp: new Date(Date.now() - 1000 * 60 * 122),
    confidence: 88,
    sources: ["OCHA", "WFP", "NGO Field Reports"],
    tags: ["famine", "armed conflict", "IDP", "aid blockade"],
    affectedPopulation: 4700000,
  },
  {
    id: "evt-009",
    title: "Taiwan Strait Air Intrusion",
    summary:
      "22 PLAAF aircraft crossed median line during live-fire naval exercise. F-16s scrambled. Tensions at 18-month high.",
    category: "GEOPOLITICAL",
    threat: "CRITICAL",
    lat: 24.1,
    lng: 120.7,
    country: "Taiwan",
    region: "East Asia",
    timestamp: new Date(Date.now() - 1000 * 60 * 145),
    confidence: 100,
    sources: ["MND Taiwan", "OSINT", "ADS-B"],
    tags: ["PLAAF", "Taiwan Strait", "airspace intrusion", "PRC"],
    affectedPopulation: 23500000,
  },
  {
    id: "evt-010",
    title: "Financial Market Manipulation",
    summary:
      "Algorithmic trading anomaly detected. $2.3B in spoofed orders across 8 exchanges. Coordinated pump-and-dump signature.",
    category: "ECONOMIC",
    threat: "MEDIUM",
    lat: 1.3,
    lng: 103.8,
    country: "Singapore",
    region: "Southeast Asia",
    timestamp: new Date(Date.now() - 1000 * 60 * 160),
    confidence: 72,
    sources: ["Exchange Feeds", "SEC Analytics", "Quant Network"],
    tags: ["market manipulation", "algo trading", "spoofing"],
    affectedPopulation: 0,
  },
];

export const MOCK_AGENTS: AIAgent[] = [
  {
    id: "agent-planner-001",
    name: "AEGIS-PLANNER",
    role: "Strategic Intelligence Planner",
    status: "ACTIVE",
    currentTask: "Synthesizing geopolitical threat vectors across 6 active theaters",
    progress: 68,
    tokensUsed: 124500,
    model: "claude-opus-4-7",
    startedAt: new Date(Date.now() - 1000 * 60 * 8),
    findings: [
      "Cross-correlation detected between Strait events and EW activity",
      "3 simultaneous disinformation campaigns share infrastructure",
      "Market anomaly timing aligns with geopolitical flashpoint",
    ],
  },
  {
    id: "agent-researcher-001",
    name: "DEEP-RESEARCH-α",
    role: "OSINT Researcher",
    status: "ANALYZING",
    currentTask: "Cross-referencing APT-41 TTPs with recent SCADA incidents",
    progress: 41,
    tokensUsed: 87200,
    model: "claude-sonnet-4-6",
    startedAt: new Date(Date.now() - 1000 * 60 * 14),
    findings: [
      "APT-41 tooling updated — new evasion layer detected",
      "4 similar SCADA targets compromised in past 90 days",
    ],
  },
  {
    id: "agent-verifier-001",
    name: "VERITY",
    role: "Verification & Fact-Check",
    status: "ACTIVE",
    currentTask: "Validating Taiwan Strait incident reports against ADS-B data",
    progress: 89,
    tokensUsed: 45600,
    model: "claude-haiku-4-5-20251001",
    startedAt: new Date(Date.now() - 1000 * 60 * 3),
    findings: [
      "ADS-B confirms 22 aircraft — 3 additional contacts untracked",
      "Timeline validated across 7 independent sources",
    ],
  },
  {
    id: "agent-risk-001",
    name: "RISKMETRIC",
    role: "Risk Analysis Engine",
    status: "ANALYZING",
    currentTask: "Modeling escalation probability for East Asia theater",
    progress: 55,
    tokensUsed: 203100,
    model: "claude-opus-4-7",
    startedAt: new Date(Date.now() - 1000 * 60 * 22),
    findings: [
      "Escalation probability: 34% within 72h window",
      "Economic decoupling threshold approaching in Q3",
    ],
  },
];

export const MOCK_STREAM_EVENTS: StreamEvent[] = [
  {
    id: "se-001",
    type: "ALERT",
    title: "CRITICAL: ICBM Engine Test Confirmed",
    body: "Thermal signature analysis confirms Paektusan-class engine test at Sohae. Pre-launch activity elevated. DEFCON watch initiated.",
    threat: "CRITICAL",
    timestamp: new Date(Date.now() - 1000 * 30),
    source: "AEGIS-SIGINT",
    isNew: true,
  },
  {
    id: "se-002",
    type: "ANALYSIS",
    title: "AI Cross-Correlation: Coordinated Operation Hypothesis",
    body: "AEGIS-PLANNER has identified statistically significant temporal clustering between 3 active threat vectors. Probability of coordination: 71%.",
    threat: "HIGH",
    timestamp: new Date(Date.now() - 1000 * 90),
    source: "AEGIS-PLANNER",
    isNew: true,
  },
  {
    id: "se-003",
    type: "UPDATE",
    title: "Taiwan Strait: Additional Aircraft Contacts",
    body: "VERITY confirms 3 untracked contacts beyond original 22. Possible stealth assets. MND Taiwan scrambling additional CAP.",
    threat: "CRITICAL",
    timestamp: new Date(Date.now() - 1000 * 180),
    source: "VERITY",
    isNew: false,
  },
  {
    id: "se-004",
    type: "AGENT",
    title: "DEEP-RESEARCH-α: New APT-41 Indicator",
    body: "Identified novel C2 domain registered 6 days prior to SCADA intrusion. Pattern matches Winnti group staging methodology.",
    threat: "HIGH",
    timestamp: new Date(Date.now() - 1000 * 300),
    source: "DEEP-RESEARCH-α",
    isNew: false,
  },
  {
    id: "se-005",
    type: "ALERT",
    title: "GPS Spoofing — Commercial Aviation Warning",
    body: "14 commercial aircraft reporting navigation anomalies in Ukrainian airspace corridor. NOTAM issued. Possible GNSS denial operation.",
    threat: "HIGH",
    timestamp: new Date(Date.now() - 1000 * 450),
    source: "AEGIS-SIGINT",
    isNew: false,
  },
  {
    id: "se-006",
    type: "SYSTEM",
    title: "Ingestion Pipeline: 847 new articles processed",
    body: "NLP classification complete. 23 HIGH/CRITICAL events extracted. 4 anomalies flagged for agent review. Vector index updated.",
    timestamp: new Date(Date.now() - 1000 * 600),
    source: "PIPELINE-ENGINE",
    isNew: false,
  },
  {
    id: "se-007",
    type: "ANALYSIS",
    title: "Financial Anomaly: Geopolitical Correlation Detected",
    body: "Market spoofing event timing correlates with Taiwan Strait escalation. Probability of informed trading: 68%. Notified SEC analytics.",
    threat: "MEDIUM",
    timestamp: new Date(Date.now() - 1000 * 780),
    source: "RISKMETRIC",
    isNew: false,
  },
];

export const MOCK_NETWORK_NODES: NetworkNode[] = [
  { id: "n1", label: "APT-41", type: "ACTOR", threat: "CRITICAL", connections: ["n2", "n3", "n7"], weight: 10, x: 300, y: 200 },
  { id: "n2", label: "SCADA Infrastructure", type: "ASSET", threat: "HIGH", connections: ["n1", "n4"], weight: 8, x: 480, y: 140 },
  { id: "n3", label: "C2 Server (AS12345)", type: "ASSET", threat: "CRITICAL", connections: ["n1", "n5", "n6"], weight: 9, x: 160, y: 120 },
  { id: "n4", label: "Power Grid", type: "ASSET", threat: "HIGH", connections: ["n2"], weight: 7, x: 600, y: 220 },
  { id: "n5", label: "LockBit 4.0", type: "ACTOR", threat: "HIGH", connections: ["n3", "n8"], weight: 8, x: 80, y: 280 },
  { id: "n6", label: "Winnti Group", type: "ORGANIZATION", threat: "HIGH", connections: ["n3", "n1"], weight: 7, x: 200, y: 60 },
  { id: "n7", label: "Sohae Facility", type: "LOCATION", threat: "CRITICAL", connections: ["n1", "n9"], weight: 9, x: 420, y: 340 },
  { id: "n8", label: "NHS Hospitals", type: "ASSET", threat: "HIGH", connections: ["n5"], weight: 6, x: 100, y: 400 },
  { id: "n9", label: "DPRK WMD Program", type: "ORGANIZATION", threat: "CRITICAL", connections: ["n7"], weight: 10, x: 540, y: 400 },
];

export const MOCK_THREAT_ZONES: ThreatZone[] = [
  { id: "tz-001", lat: 49.8, lng: 36.2, radius: 300, level: "HIGH", label: "UA Eastern Front", active: true },
  { id: "tz-002", lat: 26.5, lng: 56.3, radius: 200, level: "HIGH", label: "Hormuz Strait", active: true },
  { id: "tz-003", lat: 40.0, lng: 124.7, radius: 250, level: "CRITICAL", label: "DPRK Launch Site", active: true },
  { id: "tz-004", lat: 24.1, lng: 120.7, radius: 350, level: "CRITICAL", label: "Taiwan Strait", active: true },
  { id: "tz-005", lat: 11.9, lng: 114.3, radius: 400, level: "MEDIUM", label: "SCS Disputed Zone", active: true },
  { id: "tz-006", lat: 15.5, lng: 2.1, radius: 500, level: "HIGH", label: "Sahel Crisis", active: true },
];

export const MOCK_TIMELINE: TimelineEntry[] = [
  {
    id: "tl-001",
    title: "Taiwan Strait — 22 PLAAF Aircraft Cross Median Line",
    timestamp: new Date(Date.now() - 1000 * 60 * 145),
    category: "GEOPOLITICAL",
    threat: "CRITICAL",
    description: "Largest single intrusion in 18 months. F-16 CAP scrambled. Diplomatic channel activated.",
    isKeyEvent: true,
  },
  {
    id: "tl-002",
    title: "APT-41 SCADA Intrusion Detected",
    timestamp: new Date(Date.now() - 1000 * 60 * 180),
    category: "CYBER",
    threat: "CRITICAL",
    description: "Deep implant in US power grid SCADA systems. Novel evasion tooling identified.",
    isKeyEvent: true,
  },
  {
    id: "tl-003",
    title: "Hormuz Naval Confrontation",
    timestamp: new Date(Date.now() - 1000 * 60 * 220),
    category: "MILITARY",
    threat: "HIGH",
    description: "IRGCN vessels shadow three commercial tankers. AIS manipulation detected.",
    isKeyEvent: false,
  },
  {
    id: "tl-004",
    title: "Sohae Engine Test — Thermal Signature",
    timestamp: new Date(Date.now() - 1000 * 60 * 260),
    category: "MILITARY",
    threat: "CRITICAL",
    description: "Paektusan-class engine confirmed active. Pre-launch indicators elevated.",
    isKeyEvent: true,
  },
  {
    id: "tl-005",
    title: "LockBit 4.0 Deploys in NHS Systems",
    timestamp: new Date(Date.now() - 1000 * 60 * 310),
    category: "CYBER",
    threat: "HIGH",
    description: "$28M ransom demand. 340,000 patient records encrypted.",
    isKeyEvent: false,
  },
  {
    id: "tl-006",
    title: "Financial Market Spoofing Detected",
    timestamp: new Date(Date.now() - 1000 * 60 * 360),
    category: "ECONOMIC",
    threat: "MEDIUM",
    description: "$2.3B spoofed orders across 8 exchanges. Timing correlates with geopolitical events.",
    isKeyEvent: false,
  },
];

export const MOCK_SYSTEM_METRICS: SystemMetric[] = [
  { label: "Events/hr", value: 4847, max: 10000, unit: "", trend: "UP" },
  { label: "Active Agents", value: 4, max: 12, unit: "", trend: "STABLE" },
  { label: "Sources Online", value: 247, max: 300, unit: "", trend: "UP" },
  { label: "Threat Score", value: 78, max: 100, unit: "", trend: "UP" },
];

export const MOCK_REGION_THREATS = [
  { region: "East Asia", score: 91, events: 23 },
  { region: "Eastern Europe", score: 84, events: 31 },
  { region: "Middle East", score: 72, events: 18 },
  { region: "West Africa", score: 67, events: 12 },
  { region: "Southeast Asia", score: 58, events: 15 },
  { region: "North America", score: 54, events: 9 },
  { region: "Western Europe", score: 48, events: 7 },
];

export const MOCK_ACTIVITY_DATA = Array.from({ length: 24 }, (_, i) => ({
  hour: `${String(i).padStart(2, "0")}:00`,
  events: Math.floor(Math.random() * 80 + 20),
  threats: Math.floor(Math.random() * 30 + 5),
  cyberOps: Math.floor(Math.random() * 20 + 2),
}));

export const MOCK_MISSIONS: Mission[] = [
  {
    id: "msn-001",
    codename: "IRON SHADOW",
    type: "SURVEILLANCE",
    status: "ACTIVE",
    priority: "FLASH",
    threat: "HIGH",
    classification: "TOP SECRET",
    briefing: "Long-range surveillance operation targeting suspected command infrastructure in disputed zone. Requires persistent ISR coverage across designated sectors.",
    objective: "Establish pattern-of-life for HVT network nodes operating along northern corridor.",
    waypoints: [
      { id: "wp-001-1", lat: 48.2, lng: 37.8, label: "ORIGIN", order: 1 },
      { id: "wp-001-2", lat: 49.5, lng: 39.1, label: "SECTOR-ALPHA", order: 2 },
      { id: "wp-001-3", lat: 50.1, lng: 40.3, label: "OBJECTIVE", order: 3 },
    ],
    assignedAgents: ["researcher-001", "verifier-001"],
    createdAt: new Date(Date.now() - 86400000 * 2),
    updatedAt: new Date(Date.now() - 3600000),
    eta: "T+14H",
  },
  {
    id: "msn-002",
    codename: "PHANTOM VEIL",
    type: "CYBER_OPS",
    status: "ACTIVE",
    priority: "URGENT",
    threat: "CRITICAL",
    classification: "TOP SECRET",
    briefing: "Offensive cyber operation targeting hostile state-sponsored APT infrastructure. Network intrusion with lateral movement to C2 systems.",
    objective: "Disrupt and attribute threat actor responsible for SIDEWINDER campaign.",
    waypoints: [
      { id: "wp-002-1", lat: 39.9, lng: 116.4, label: "TARGET-PRIMARY", order: 1 },
      { id: "wp-002-2", lat: 37.5, lng: 127.0, label: "TARGET-SECONDARY", order: 2 },
    ],
    assignedAgents: ["risk-001"],
    createdAt: new Date(Date.now() - 86400000),
    updatedAt: new Date(Date.now() - 7200000),
    eta: "T+2H",
  },
  {
    id: "msn-003",
    codename: "SILVER COMPASS",
    type: "DIPLOMATIC",
    status: "PLANNING",
    priority: "ROUTINE",
    threat: "MEDIUM",
    classification: "CONFIDENTIAL",
    briefing: "Covert diplomatic channel establishment to facilitate back-channel negotiations on regional de-escalation framework.",
    objective: "Secure preliminary agreement for ceasefire monitoring protocol.",
    waypoints: [
      { id: "wp-003-1", lat: 41.0, lng: 29.0, label: "RENDEZVOUS", order: 1 },
      { id: "wp-003-2", lat: 33.9, lng: 35.5, label: "MEETING-POINT", order: 2 },
    ],
    assignedAgents: [],
    createdAt: new Date(Date.now() - 3600000 * 5),
    updatedAt: new Date(Date.now() - 3600000 * 5),
    eta: "T+72H",
  },
  {
    id: "msn-004",
    codename: "DEEP ANCHOR",
    type: "RECONNAISSANCE",
    status: "COMPLETE",
    priority: "URGENT",
    threat: "HIGH",
    classification: "SECRET",
    briefing: "Ground-truth reconnaissance of suspected weapons storage facility. HumInt confirmation required prior to kinetic authorization.",
    objective: "Physical confirmation of facility coordinates and activity assessment.",
    waypoints: [
      { id: "wp-004-1", lat: 33.3, lng: 44.4, label: "INGRESS", order: 1 },
      { id: "wp-004-2", lat: 33.8, lng: 43.9, label: "OBJECTIVE", order: 2 },
      { id: "wp-004-3", lat: 32.9, lng: 44.8, label: "EGRESS", order: 3 },
    ],
    assignedAgents: ["researcher-001", "researcher-002"],
    createdAt: new Date(Date.now() - 86400000 * 5),
    updatedAt: new Date(Date.now() - 86400000),
    eta: "COMPLETE",
  },
  {
    id: "msn-005",
    codename: "ARCTIC GHOST",
    type: "EXTRACTION",
    status: "ON_HOLD",
    priority: "FLASH",
    threat: "CRITICAL",
    classification: "TOP SECRET",
    briefing: "Emergency exfiltration of compromised HUMINT asset. Primary exfil route compromised. Awaiting alternate route authorization.",
    objective: "Extract CARDINAL-7 and handler from denied area within 48-hour window.",
    waypoints: [
      { id: "wp-005-1", lat: 59.9, lng: 30.3, label: "PICKUP", order: 1 },
      { id: "wp-005-2", lat: 60.5, lng: 24.9, label: "SAFE-HOUSE", order: 2 },
      { id: "wp-005-3", lat: 60.2, lng: 25.0, label: "EXTRACTION", order: 3 },
    ],
    assignedAgents: ["planner-001"],
    createdAt: new Date(Date.now() - 3600000 * 12),
    updatedAt: new Date(Date.now() - 1800000),
    eta: "PENDING",
  },
];
