/**
 * Defined threat levels for events and missions.
 */
export type ThreatLevel = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "NOMINAL";

/**
 * Functional categories for intelligence events.
 */
export type EventCategory =
  | "MILITARY"
  | "CYBER"
  | "GEOPOLITICAL"
  | "ECONOMIC"
  | "HUMANITARIAN"
  | "NATURAL"
  | "HEALTH"
  | "INTELLIGENCE"
  | "SPACE"
  | "NUCLEAR";

/**
 * Operational status of an AI agent.
 */
export type AgentStatus = "ACTIVE" | "ANALYZING" | "IDLE" | "COMPLETE" | "ERROR";

/**
 * Represents a geographic intelligence event.
 */
export interface GeoEvent {
  id: string;
  title: string;
  summary: string;
  category: EventCategory;
  threat: ThreatLevel;
  lat: number;
  lng: number;
  country: string;
  region: string;
  timestamp: Date;
  /** Confidence score from 0 to 100 */
  confidence: number;
  sources: string[];
  tags: string[];
  affectedPopulation?: number;
}

/**
 * Represents an active AI analysis agent.
 */
export interface AIAgent {
  id: string;
  name: string;
  role: string;
  status: AgentStatus;
  currentTask: string;
  /** Completion progress from 0 to 100 */
  progress: number;
  tokensUsed: number;
  model: string;
  startedAt: Date;
  findings: string[];
}

/**
 * A comprehensive intelligence report generated by agents.
 */
export interface IntelligenceReport {
  id: string;
  title: string;
  classification: "UNCLASSIFIED" | "CONFIDENTIAL" | "SECRET" | "TOP SECRET";
  summary: string;
  threat: ThreatLevel;
  regions: string[];
  generatedAt: Date;
  agentId: string;
  confidence: number;
  keyFindings: string[];
  recommendations: string[];
}

/**
 * An event entry in the real-time activity stream.
 */
export interface StreamEvent {
  id: string;
  type: "ALERT" | "UPDATE" | "ANALYSIS" | "AGENT" | "SYSTEM";
  title: string;
  body: string;
  threat?: ThreatLevel;
  timestamp: Date;
  source: string;
  isNew?: boolean;
}

/**
 * A node in the intelligence relationship network graph.
 */
export interface NetworkNode {
  id: string;
  label: string;
  type: "ACTOR" | "LOCATION" | "EVENT" | "ORGANIZATION" | "ASSET";
  threat?: ThreatLevel;
  x?: number;
  y?: number;
  connections: string[];
  weight: number;
}

/**
 * High-level system performance and health metrics.
 */
export interface SystemMetric {
  label: string;
  value: number;
  max: number;
  unit: string;
  trend: "UP" | "DOWN" | "STABLE";
}

/**
 * Defined geographic zone of elevated threat.
 */
export interface ThreatZone {
  id: string;
  lat: number;
  lng: number;
  radius: number;
  level: ThreatLevel;
  label: string;
  active: boolean;
}

/**
 * A specific point in time entry for the chronological timeline.
 */
export interface TimelineEntry {
  id: string;
  title: string;
  timestamp: Date;
  category: EventCategory;
  threat: ThreatLevel;
  description: string;
  isKeyEvent: boolean;
}

/**
 * Lifecycle status of a mission.
 */
export type MissionStatus = "PLANNING" | "ACTIVE" | "ON_HOLD" | "COMPLETE" | "COMPROMISED" | "ABORTED";

/**
 * Tactical type of mission.
 */
export type MissionType   = "RECONNAISSANCE" | "EXTRACTION" | "SURVEILLANCE" | "CYBER_OPS" | "DIPLOMATIC" | "STRIKE";

/**
 * Geographic waypoint for mission navigation.
 */
export interface MissionWaypoint {
  id:    string;
  lat:   number;
  lng:   number;
  label: string;
  order: number;
}

/**
 * Represents a tactical mission managed by AEGIS.
 */
export interface Mission {
  id:          string;
  codename:    string;
  type:        MissionType;
  status:      MissionStatus;
  priority:    "FLASH" | "URGENT" | "ROUTINE";
  threat:      ThreatLevel;
  briefing:    string;
  objective:   string;
  waypoints:   MissionWaypoint[];
  assignedAgents: string[];
  createdAt:   Date;
  updatedAt:   Date;
  eta?:        string;
  classification: "UNCLASSIFIED" | "CONFIDENTIAL" | "SECRET" | "TOP SECRET";
}
